### ISSUE TITLE
Some questions about Experimental settings

### ISSUE THREAD

**Issue by a1b2c3s4d4** [hasanirtiza/PedesFormer#7]
Hi, I am studying your paper 《Pedestrian Detection: Domain Generalization, CNNs, Transformers and Beyond》. What does the height in Table 1 on the third page of the paper mean? Why is it set up like this? Thank you so much! ! !
<img width="326" alt="1" src="https://github.com/hasanirtiza/PedesFormer-Transformer-Networks-For-Pedestrian-Detection/assets/42224576/b20860b7-245e-4acd-8a57-b5e59e418467">

**Comment by hasanirtiza** [comment]
Hi,
Height in Table 1, refers to height of pedestrian in pixels. So in simple terms, during evaluation, for example under **Reasonable** setting,  you only take into account pedestrian whose height is greater than 50 pixel using ground truth. Now, the second question, why is like that, I suggest you to [read this paper](https://pdollar.github.io/files/papers/DollarPAMI12peds.pdf), particularly section 2, 3 and figure 4. In summary, it is shown that due to application oriented nature of the problem, these settings were found to be most meaningful (for autonomous vehicles etc).
